# Generated by Django 5.2.6 on 2025-09-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('backCover', models.TextField()),
                ('cover', models.BooleanField(default=False)),
            ],
        ),
    ]
