# Generated by Django 5.2.6 on 2025-10-21 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonnes_lectures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('texte', models.CharField(max_length=250)),
                ('concerns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonnes_lectures.book')),
            ],
        ),
    ]
