# Generated by Django 5.2.6 on 2025-10-21 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonnes_lectures', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='texte',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='review',
            name='concerns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bonnes_lectures.book'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
