# Generated by Django 5.2.6 on 2025-10-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonnes_lectures', '0003_rename_texte_review_text_alter_review_concerns_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='concerns',
            new_name='book',
        ),
    ]
